apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx-warehouse
    sources:
      stages:
      - dev
